# Generated by Django 3.1.2 on 2020-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expected_harvest', models.CharField(max_length=100)),
                ('expected_expenditure', models.IntegerField()),
                ('expected_income', models.IntegerField()),
                ('soil_type', models.CharField(max_length=50)),
                ('irrigation_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('water_requirement', models.CharField(max_length=100)),
            ],
        ),
    ]
